### ISSUE TITLE
Hey Corp, this is weird?!

### ISSUE THREAD

**Issue by macmeister1967** [corpnewt/Lilu-and-Friends#16]
#######################################################
 #                 0 of 1 Succeeded                    #
#######################################################
 
Succeeded:

    None

Failed:

    IntelGraphicsFixup
 
Build took 31 seconds.

Press [enter] to return to the main menu...

(Lilu.kext built correctly each time...)

**Comment by corpnewt** [comment]
Hey macmeister - vit was in the process of migrating a number of kexts into WhateverGreen recently (specifically CoreDisplayFixup, IntelGraphicsFixup, NvidiaGraphicsFixup, and Shiki).  Because of this - IntelGraphicsFixup wasn't getting the love it needed after Lilu received an update.  I updated the main script to migrate existing profiles and it builds WEG successfully.
