### ISSUE TITLE
strange issue

### ISSUE THREAD

**Issue by Sher1ocks** [corpnewt/Lilu-and-Friends#25]
i build latest lilu and friends source.
2019/7/18 8:51 pm.
after built kexts and put them in other folder, then boot, 
some kext load was failed. is it source issue?

**Comment by corpnewt** [comment]
Hey Sherlocks,

Which kexts?  And what version of macOS & Clover are you running?  I can test here to verify.

-CorpNewt

**Comment by Sher1ocks** [comment]
> Hey Sherlocks,
> 
> Which kexts? And what version of macOS & Clover are you running? I can test here to verify.
> 
> -CorpNewt

hi. Whatevergreen.
can you built WEG kext?

my system has 10.15 beta3 now. 

also can you fix this issue when your script start?
  #######################################################
 #                  Downloading iasl                   #
#######################################################

Downloading iasl.zip...
 - Extracting...
An error occurred :(

You can download the iasl binary from here:

https://bitbucket.org/RehabMan/acpica/downloads/iasl.zip

Extract that zip, then place iasl in the Scripts folder in the
Lilu and Friends folder.

Press [enter] to continue...

also still fail built NightShiftUnlocker

thanks in advance

**Comment by corpnewt** [comment]
I just tested WEG on 10.14.6 (18G78a) - I'll build it on my 10.15 machine shortly too, and all went fine.

NightShiftUnlocker failed to build - but looking at the github repo implies that it's heavily outdated.  There's [a pull request](https://github.com/0xFireWolf/NightShiftUnlocker/pull/13) that adds more recent support - and I tested it on the same Mojave machine, and it built:

![image](https://user-images.githubusercontent.com/12772521/61457633-5e77a580-a92e-11e9-8ea2-f11ff3af9881.png)


As for the download error - are you on python 3.6 or later by chance?  If so - check in your `/Applications/Python 3.X` (where X is the sub version) folder, and run the "Install Certificates.command".  Python 3.6 and newer have some issues with OpenSSL certs - and require this secondary script be run in order to fix them.

I'll verify both WEG and the new NSU kext build on 10.15 - then I'll push the updated code.

-CorpNewt

**Comment by corpnewt** [comment]
Just tested on 10.15 beta 4 (19A512f), and both kexts built fine:

![image](https://user-images.githubusercontent.com/12772521/61461786-06916c80-a937-11e9-8f62-350b595e53ca.png)

I tested with Python 2.7.16 and 3.7.4 (with the updated certs).

-CorpNewt

**Comment by Sher1ocks** [comment]
> Just tested on 10.15 beta 4 (19A512f), and both kexts built fine:
> 
> ![image](https://user-images.githubusercontent.com/12772521/61461786-06916c80-a937-11e9-8f62-350b595e53ca.png)
> 
> I tested with Python 2.7.16 and 3.7.4 (with the updated certs).
> 
> -CorpNewt

thank you for resolved issue and update and tip.
seems build is no problem. recently WEG source changed. seems it causes issue.
other kexts are no problem.

**Comment by Sher1ocks** [comment]
suggestion.
can you add build option for debug kext?
it help to debug each kext with bootarg lilu debug option if need check kernel log

**Comment by corpnewt** [comment]
I can look into adding a debug option at some point - I'm not sure if I'll have to refactor a ton... or very little of the code.  It's been a bit since I dove into the internals of this script haha - most of the updates are just to the plugin list.

As for the issue you had initially - is that resolved?  If so, I'll go ahead and close this issue.

-CorpNewt

**Comment by Sher1ocks** [comment]
> I can look into adding a debug option at some point - I'm not sure if I'll have to refactor a ton... or very little of the code. It's been a bit since I dove into the internals of this script haha - most of the updates are just to the plugin list.
> 
> As for the issue you had initially - is that resolved? If so, I'll go ahead and close this issue.
> 
> -CorpNewt

yes resolved for my issue at least.  thank you for help

if you add to divide release(default)/debug kext build option, it will help developer for debug.

**Comment by corpnewt** [comment]
I added a [rudimentary debugging option](https://github.com/corpnewt/Lilu-and-Friends/commit/07b0fcc28c78fbc3221762bd42d18fc63025c4e3) - it's not perfect, but I'm not sure of a more elegant way without rewriting a large portion of the existing code or doubling up the kext entries.

You can enable it via the `TD. Toggle Building Debug Kexts` option in the main menu.  Not all kexts support Debug configurations, but in my tests, I could build all but the`HWSensors (FakeSMC + Plugins)` option (but that also wouldn't build without Debugging - so I'm guessing some code in the repo is conflicting).

Hopefully that helps make things easier.

-CorpNewt

**Comment by Sher1ocks** [comment]
thank you so much :)
have a good day
