### ISSUE TITLE
Whether you can add a kext name to the selection menu list

### ISSUE THREAD

**Issue by 1xiaocainiao** [corpnewt/Lilu-and-Friends#37]
Thank you for sharing such a great tool,  but add a kext name to the selection menu list to make it easier to distinguish

**Comment by corpnewt** [comment]
Hey there - not sure what you mean?

-CorpNewt

**Comment by 1xiaocainiao** [comment]
> Hey there - not sure what you mean?
> 
> -CorpNewt


![image](https://user-images.githubusercontent.com/7066030/122175459-46ac5180-ceb6-11eb-811f-d2aecd4cecd5.png)
As shown in the figure above, this list of serial numbers has only a description of each driver, not a name, which is sometimes not easy to find

**Comment by corpnewt** [comment]
There's a color picker that you can access from the main menu (`C.  Color Picker`) that lets you change the different custom colors in the script:

![image](https://user-images.githubusercontent.com/12772521/122231031-c2d77280-ce7f-11eb-9e82-9fc96f399a82.png)

I've just pushed a few commits that allow for auto-detection of dark mode, which will select white-bold by default instead of black-bold.  This should make the kext names more legible:

![image](https://user-images.githubusercontent.com/12772521/122231426-0f22b280-ce80-11eb-8008-e9cd6b15cf2b.png)

Hopefully that helps,

-CorpNewt

**Comment by 1xiaocainiao** [comment]
> There's a color picker that you can access from the main menu (`C. Color Picker`) that lets you change the different custom colors in the script:
> 
> ![image](https://user-images.githubusercontent.com/12772521/122231031-c2d77280-ce7f-11eb-9e82-9fc96f399a82.png)
> 
> I've just pushed a few commits that allow for auto-detection of dark mode, which will select white-bold by default instead of black-bold. This should make the kext names more legible:
> 
> ![image](https://user-images.githubusercontent.com/12772521/122231426-0f22b280-ce80-11eb-8008-e9cd6b15cf2b.png)
> 
> Hopefully that helps,
> 
> -CorpNewt

Thank you very much.
